service: try-sls-deploy-from-artifact02_03

provider:
  name: aws
  runtime: java8
  stage: dev
  region: ap-northeast-1

package:
  artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.2.zip
  individually: false

functions:
  hello:
    handler: com.serverless.Handler
    package:
      individually: true
      artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.1.zip

  goodbye:
    handler: com.serverless.HandlerGoodBye
