service: try-sls-deploy-from-artifact02

provider:
  name: aws
  runtime: java8
  stage: dev
  region: ap-northeast-1

package:
  artifact: build/distributions/hello.zip

functions:
  hello:
    handler: com.serverless.Handler

  goodbye:
    handler: com.serverless.HandlerGoodBye
